export const DAY_TYPE = {
    'Mo': 0,
    'Tu': 1,
    'We': 2,
    'Th': 3,
    'Fr': 4,
    'Sa': 5,
    'Su': 6
}


export const MONDAY = [
    {'day':'Mo','coding_hours':0,'reading_hours':0,'lines':0,'word_typed':0},
    {'day':'Tu','coding_hours':0,'reading_hours':0,'lines':0,'word_typed':0},
    {'day':'We','coding_hours':0,'reading_hours':0,'lines':0,'word_typed':0},
    {'day':'Th','coding_hours':0,'reading_hours':0,'lines':0,'word_typed':0},
    {'day':'Fr','coding_hours':0,'reading_hours':0,'lines':0,'word_typed':0},
    {'day':'Sa','coding_hours':0,'reading_hours':0,'lines':0,'word_typed':0},
    {'day':'Su','coding_hours':0,'reading_hours':0,'lines':0,'word_typed':0}
]


export const Language = [
    {'language':'bat','long': 0},
    {'language':'c','long': 0},
    {'language':'csharp','long': 0},
    {'language':'cpp','long': 0},
    {'language':'css','long': 0},
    {'language':'cuda-cpp','long': 0},
    {'language':'clojure','long': 0},
    {'language':'coffeescript','long': 0},
    {'language':'dockercompose','long': 0},
    {'language':'dart','long': 0},
   { 'language':'diff','long': 0},
    {'language':'coffeescript','long': 0},
    {'language':'javascript','long': 0},
    {'language':'javascriptreact','long': 0},
    {'language':'html','long': 0},
    {'language':'json','long': 0},
    {'language':'java','long': 0},
    {'language':'perl','long': 0},
    {'language':'razor','long': 0},
    {'language':'ruby','long': 0},
    {'language':'sql','long': 0},
    {'language':'swift','long': 0},
    {'language':'typescriptreact','long': 0},
    {'language':'typescript','long':0},
    {'language':'mongodb','long': 0},
    {'language':'plaintext','long': 0},
    {'language':'powershell','long': 0},
    {'language':'python','long': 0},
    {'language':'log','long': 0},
]
export const Language_SET = {
    'bat': 1,
    'c': 2,
    'csharp': 3,
    'cpp': 4,
    'css': 5,
    'cuda-cpp': 6,
    'clojure': 7,
    'coffeescript': 8,
    'dockercompose': 9,
    'dart': 10,
    'diff': 11,
    'coffeescript': 12,
    'javascript': 13,
    'javascriptreact': 14,
    'html': 15,
    'json': 16,
    'java': 17,
    'perl': 18,
    'razor': 19,
    'ruby': 20,
    'sql': 21,
    'swift': 22,
    'typescriptreact': 23,
    'typescript': 24,
    'mongodb': 25,
    'plaintext': 26,
    'powershell': 27,
    'python': 28,
    'log': 29,
}
